/**
 * Used to control the data that gets attached to DtoBaseItems.
 * @export
 * @enum {string}
 */
export enum ItemFields {
  AirTime = 'AirTime',
  CanDelete = 'CanDelete',
  CanDownload = 'CanDownload',
  Chapters = 'Chapters',
  ChildCount = 'ChildCount',
  CumulativeRunTimeTicks = 'CumulativeRunTimeTicks',
  DateCreated = 'DateCreated',
  DateLastMediaAdded = 'DateLastMediaAdded',
  DisplayPreferencesId = 'DisplayPreferencesId',
  Etag = 'Etag',
  ExternalUrls = 'ExternalUrls',
  Genres = 'Genres',
  HomePageUrl = 'HomePageUrl',
  ItemCounts = 'ItemCounts',
  MediaSourceCount = 'MediaSourceCount',
  MediaSources = 'MediaSources',
  OriginalTitle = 'OriginalTitle',
  Overview = 'Overview',
  ParentId = 'ParentId',
  Path = 'Path',
  People = 'People',
  ProviderIds = 'ProviderIds',
  PrimaryImageAspectRatio = 'PrimaryImageAspectRatio',
  RecursiveItemCount = 'RecursiveItemCount',
  Settings = 'Settings',
  SeriesPrimaryImage = 'SeriesPrimaryImage',
  SortName = 'SortName',
  Studios = 'Studios',
  Taglines = 'Taglines',
  Tags = 'Tags',
  MediaStreams = 'MediaStreams',
  SeasonUserData = 'SeasonUserData',
  ServiceName = 'ServiceName'
}
